### ISSUE TITLE
Composum broken in develop-sling12

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#569]
Something is wrong with **Composum** in [develop-sling12](https://github.com/headwirecom/peregrine-cms/tree/develop-sling12):

![Composum](https://user-images.githubusercontent.com/5563546/94014411-c71ca680-fdab-11ea-811c-3f569e965b56.png)

The cause is a `js` exception, not the above mentioned access issues:

![js](https://user-images.githubusercontent.com/5563546/94014504-ec111980-fdab-11ea-8dba-9248cc524803.png)

The instance was started just like in [568](https://github.com/headwirecom/peregrine-cms/issues/568).

**Comment by reusr1** [comment]
@reggie7 have you tried clearing caches? I currently do not see this issue but I also remember somebody else having an issue with composum and sling9 that was caused by a javascript error like this.

**Comment by reggie7** [comment]
Sadly I have cleared cache, tried incognito too...

**Comment by cmrockwell** [comment]
Some questions that maybe will help figure out what's happening.

1. What does `java -version` report for Java version?
2. Can you report details about the bundles http://localhost:8080/system/console/bundles 
- How many active? How many installed? Any other statuses?
3. Do you see response codes 503 for any URL's? For example, does http://localhost:8080/system/sling/form/login work?

I have other hunches, but lets start here

**Comment by reusr1** [comment]
@reggie7 and you try again? for me at least this is fixed by https://github.com/headwirecom/peregrine-cms/commit/f4735263c769e37aafcffddbae72595063aad7c2

**Comment by reggie7** [comment]
@cmrockwell 

```
W:\>java -version
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
```

All bundles up and running. No 503, login page is working.

**Comment by cmrockwell** [comment]
My understanding was that it was resolved by ensuring settings for the admin allowlist were properly effective.
As mentioned in this [Composum issue 105](https://github.com/ist-dresden/composum/issues/105), their bundles require loginAdministrative, and that needs to be configured.


If someone experiences this type of issue, they can confirm first whether /system/console/configMgr has the admin settings shown below
<img width="1384" alt="Screen Shot 2020-10-16 at 11 06 47 AM" src="https://user-images.githubusercontent.com/1811207/96275834-38f9a180-0fa0-11eb-9479-ea3fae10f924.png">

Specifically they can confirm there is an entry for composum 
<img width="1388" alt="Screen Shot 2020-10-16 at 11 06 36 AM" src="https://user-images.githubusercontent.com/1811207/96275842-3b5bfb80-0fa0-11eb-8d45-57bbec0ee5c6.png">

This configuration should be applied for Composum, based on this feature definition
https://github.com/headwirecom/peregrine-cms/blob/develop-sling12/sling/peregrine-builder-sling-12/src/main/features/app/composum.json

I've heard reports that possibly restarting the instance might be needed, ymmv. However if not, then possibly review how Peregrine is launched in Sling12
https://github.com/headwirecom/peregrine-cms/blob/develop-sling12/sling/peregrine-builder-sling-12/README.md

Hopefully that helps

**Comment by reusr1** [comment]
closing this issue as this is solved by using the launcher/far from https://github.com/peregrine-cms/peregrine-builder - we had a bad repoinit script and an older version of composum configured

**Comment by reggie7** [comment]
@reusr1 I don't think the issue is fixed. Just checked it on Windows machine on [`peregrine-builder/develop`](https://github.com/peregrine-cms/peregrine-builder) + [peregrine-cms/develop-sling12](https://github.com/headwirecom/peregrine-cms/tree/develop-sling12) and the result is the same.

**Comment by reggie7** [comment]
@KWoloszczuk has the same problem. An I've just confirmed that with [`peregrine-builder/develop`](https://github.com/peregrine-cms/peregrine-builder) alone (prior to installing Peregrine).

**Comment by ehdatheadwire** [comment]
@reggie7 and @reusr1 please confirm if this is still an issue and, if so, if it is required for 1.0.0 release. Marking ticket as close please / move :) .

**Comment by reusr1** [comment]
@ehdatheadwire it is still an issue but it seems to be limited to windows installations and seems to be an issue in https://github.com/apache/sling-org-apache-sling-starter (outside of the peregrine project). I have been trying to find the root cause of the issue in that project but have not been successful yet. getting closer :-)

**Comment by reusr1** [comment]
this issue is now limited to windows 10 and some newer jvm's - the problem is that some content from the initial bundle content are created as files instead of a node structure - the problem is tracked as well in https://github.com/ist-dresden/composum-nodes/issues/220
